---
- hosts: all
  gather_facts: true
  connection: local

  tasks:
    - name: set multiple users to privilege level 15
      ios_user:
        aggregate:
          - name: asantana
          - name: rbautista
        privilege: 15
        state: present
